//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllComment
    {
        public string user_cnic { get; set; }
        public string user_name { get; set; }
        public string user_picture { get; set; }
        public int comment_id { get; set; }
        public string comment_text { get; set; }
        public System.DateTime comment_date { get; set; }
        public int post_id { get; set; }
    }
}
