//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V1Entities : DbContext
    {
        public V1Entities()
            : base("name=V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<Journalist> Journalists { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Politician> Politicians { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<UpgradeRequset> UpgradeRequsets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AllComment> AllComments { get; set; }
        public virtual DbSet<AllPost> AllPosts { get; set; }
        public virtual DbSet<AllReport> AllReports { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
