//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Politician
    {
        public int id { get; set; }
        public string politicain_position { get; set; }
        public string politician_type { get; set; }
        public string User_cnic { get; set; }
        public string Party_name { get; set; }
    
        public virtual User User { get; set; }
    }
}
