//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int id { get; set; }
        public int rate_score { get; set; }
        public System.DateTime rate_date { get; set; }
        public int Post_id { get; set; }
        public string User_cnic { get; set; }
        public int pop_score { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
