//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public System.DateTime report_date { get; set; }
        public string report_status { get; set; }
        public string report_type { get; set; }
        public string report_reason { get; set; }
        public string User_cnic { get; set; }
        public int Post_id { get; set; }
        public int Comment_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
