//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpgradeRequset
    {
        public int id { get; set; }
        public string request_type { get; set; }
        public string request_status { get; set; }
        public string request_document { get; set; }
        public string User_cnic { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public string platform { get; set; }
        public string position { get; set; }
        public string objection { get; set; }
    
        public virtual User User { get; set; }
    }
}
