//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string user_cnic { get; set; }
        public string user_name { get; set; }
        public string user_picture { get; set; }
        public string user_type { get; set; }
        public Nullable<int> user_total_post { get; set; }
        public string user_position { get; set; }
        public Nullable<int> user_total_followed { get; set; }
        public Nullable<int> user_total_following { get; set; }
        public string user_province { get; set; }
        public string user_distinct { get; set; }
        public string user_tehsil { get; set; }
        public string user_uc { get; set; }
        public string user_phone { get; set; }
        public string user_gender { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string is_follow { get; set; }
    }
}
